#!/bin/bash
(
    # List untracked files.
    # -z (null-separated output) is used in case the filenames contain spaces,
    # in which case git ls-files would add quotes without -z.
    git ls-files -z -o --exclude-standard
    # List files that have changed since the last commit.
    git diff -z --name-only --diff-filter ACMRTUB HEAD
) \
    | tr '\0' '\n' \
    | grep '\.ts$' \
    | xargs -r pnpm tsfmt -r --useTsfmt dev/config/tsfmt.json
