#!/bin/bash

set -euo pipefail

HERE="$(dirname "$0")"
ROOT="$(cd "$HERE/../.." && pwd)"
cd "$ROOT"

if ! grep -qE '^ref: refs/heads/main$' .git/HEAD; then
    >&2 echo
    >&2 echo "Error: you must be on the 'main' branch to release."
    exit 1
fi

STATUS="$(git status --porcelain)"

if \
    [ "$(wc -l <<<"$STATUS")" -ne 1 ] \
    || ! grep -qE '^[MA? ][MA? ] pkg/([^/]+)/CHANGELOG.md$' <<<"$STATUS"
then
    >&2 echo
    >&2 echo "Error: your working tree is not in a felicitous state."
    >&2 echo "Update one CHANGELOG.md file and try again."
    exit 1
fi

PACKAGE="$(cut -d/ -f2 <<<"$STATUS")"
CHANGELOG="$(cut -b4- <<<"$STATUS")"
VERSION="$(grep ^## "$CHANGELOG" | head -n1 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\S*' || true)"
DATE="$(grep ^## "$CHANGELOG" | head -n1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}' || true)"
TAG="@longlast/$PACKAGE@$VERSION"

if [ -z "$VERSION" ]; then
    >&2 echo
    >&2 echo "Error: version in $CHANGELOG is malformed."
    exit 1
fi

if [ "$DATE" != "$(date -I)" ]; then
    >&2 echo
    >&2 echo "Error: date in $CHANGELOG is wrong. Expected $(date -I)."
    exit 1
fi

# Bump the version in package.json.
pushd "$ROOT/pkg/$PACKAGE" >/dev/null
    pnpm version "$VERSION" --git-tag-version false
popd >/dev/null

# Create a copy of the working tree in which to build the release.
RELEASE_DIR="$("$HERE/clone-worktree")"
>&2 echo "RELEASE_DIR='$RELEASE_DIR'"

# Build it!
pushd "$RELEASE_DIR" >/dev/null
    make deps
    make verify
    make build
    pnpm pack --recursive
popd >/dev/null

# Commit and tag the version bump.
git add "$ROOT/pkg/$PACKAGE/package.json"
git add "$ROOT/pkg/$PACKAGE/CHANGELOG.md"
git commit -m "Release $TAG"
git tag "$TAG"

cat <<EOF

Almost done! Remaining manual steps:

    pnpm publish --access public '$RELEASE_DIR/longlast-$PACKAGE-$VERSION.tgz'
    git push origin main --tags
EOF
