#!/bin/bash

set -euo pipefail

HERE="$(dirname "$0")"

BUILD="$($HERE/clone_worktree 2>/dev/null)"
CLIENT="$($HERE/clone_worktree 2>/dev/null)"

{
    pushd "$BUILD"
        make deps
        make build
        pnpm pack --recursive
    popd
} >/dev/null

pushd "$CLIENT" >/dev/null
    {
        rm -rf pnpm-workspace.yaml packages
        make deps
        pnpm add "$BUILD"/longlast-*.tgz
        pushd "$BUILD"
            ls -d packages/*/package-tests | \
                xargs -I{} cp -r --parents {} "$CLIENT"
        popd
        find packages -type f | xargs sed -ie 's/@ts-nocheck//'
    } >/dev/null
    pnpm tsc
popd >/dev/null
